format = '''
$time $all$os$status$container$shell$character
'''
## Line One
# First param ─┌
# Prompt: optional param 1
[time]
format = " [╭─](bold red)\\[[$time]($style)\\]"
style = "bold bright-green"
time_format = "%F %T"
disabled = false

[username]
format = "➜ [$user]($style)@"
style_user = "bold yellow"
style_root = "bold green"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold green"
trim_at = ".naedge."
ssh_only = false
disabled = false

# Third param
[directory]
style = "purple"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false

## Line 2
# Prompt: param 2 └─
[character]
success_symbol = "─➤ [√](bold green)"
error_symbol = "─➤ [×](bold red)"

# SYMBOLS
[status]
format = ' [\[$symbol - $status\]]($style) '
map_symbol = true
disabled = false

[os]
format = " [╰─](bold red) [$symbol $name]($style) ─"
style = "bold blue"
disabled = false

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[python]
symbol = " "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[nodejs]
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

# Nerd Font Symbol
[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[haskell]
symbol = "λ "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[aws]
symbol = " "
disabled = true

[conda]
symbol = " "

[dart]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Linux = " "
Macos = " "
Manjaro = " "
openSUSE = " "
Redhat = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
