#!/usr/bin/env bash
# Reads accounts/*.conf and generates configs for mbsync, msmtp, neomutt, notmuch.
#   bash ~/.dotfiles/mail/gen.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ACCOUNTS_DIR="${SCRIPT_DIR}/accounts"
MUTT_ACCOUNTS="${SCRIPT_DIR}/mutt/accounts"
ISYNC_DIR="${SCRIPT_DIR}/isync"
MSMTP_DIR="${SCRIPT_DIR}/msmtp"
NOTMUCH_DIR="${SCRIPT_DIR}/notmuch"

MAIL_ROOT="${HOME}/.local/share/mail"
CACHE_ROOT="${HOME}/.cache/mutt"

GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}✓${NC} $*"; }
die()  { echo -e "${RED}✗${NC} $*" >&2; exit 1; }

# ─── Collect accounts ────────────────────────────────────────────────────────

accounts=()
for f in "${ACCOUNTS_DIR}"/*.conf; do
    [[ "$(basename "$f")" == "example.conf" ]] && continue
    [[ -f "$f" ]] || continue
    accounts+=("$f")
done

(( ${#accounts[@]} )) || die "No account configs in ${ACCOUNTS_DIR}/. Copy example.conf to get started."

# ─── Parse one account conf ──────────────────────────────────────────────────

load_account() {
    ACCOUNT="" FULLNAME="" EMAIL="" PASS_ENTRY="" FROM_ADDRESS=""
    TYPE="generic" IMAP_HOST="" IMAP_PORT="993" SMTP_HOST="" SMTP_PORT="587"

    # shellcheck source=/dev/null
    source "$1"

    FROM_ADDRESS="${FROM_ADDRESS:-${EMAIL}}"

    [[ "${TYPE}" == "gmail" ]] && {
        IMAP_HOST="${IMAP_HOST:-imap.gmail.com}"
        SMTP_HOST="${SMTP_HOST:-smtp.gmail.com}"
    }

    [[ -n "${ACCOUNT}" && -n "${EMAIL}" && -n "${PASS_ENTRY}" ]] \
        || die "$1: ACCOUNT, EMAIL, and PASS_ENTRY are required."
    [[ "${TYPE}" != "generic" || (-n "${IMAP_HOST}" && -n "${SMTP_HOST}") ]] \
        || die "$1: generic type requires IMAP_HOST and SMTP_HOST."
}

# ─── Gmail folder map (Far → Near) ───────────────────────────────────────────

gmail_channels() {
    local a="$1"
    cat <<EOF
Channel ${a}-inbox
Far     :${a}-remote:INBOX
Near    :${a}-local:Inbox

Channel ${a}-sent
Far     :${a}-remote:"[Gmail]/Sent Mail"
Near    :${a}-local:Sent
Create  Near

Channel ${a}-drafts
Far     :${a}-remote:"[Gmail]/Drafts"
Near    :${a}-local:Drafts
Create  Near

Channel ${a}-trash
Far     :${a}-remote:"[Gmail]/Trash"
Near    :${a}-local:Trash
Create  Near

Channel ${a}-archive
Far     :${a}-remote:"[Gmail]/All Mail"
Near    :${a}-local:Archive
Create  Near

Group ${a}
Channel ${a}-inbox
Channel ${a}-sent
Channel ${a}-drafts
Channel ${a}-trash
Channel ${a}-archive
EOF
}

generic_channels() {
    local a="$1"
    cat <<EOF
Channel ${a}-inbox
Far     :${a}-remote:INBOX
Near    :${a}-local:Inbox

Channel ${a}-sent
Far     :${a}-remote:Sent
Near    :${a}-local:Sent
Create  Near

Channel ${a}-drafts
Far     :${a}-remote:Drafts
Near    :${a}-local:Drafts
Create  Near

Channel ${a}-trash
Far     :${a}-remote:Trash
Near    :${a}-local:Trash
Create  Near

Group ${a}
Channel ${a}-inbox
Channel ${a}-sent
Channel ${a}-drafts
Channel ${a}-trash
EOF
}

# ─── Generate isync/mbsyncrc ─────────────────────────────────────────────────

gen_mbsyncrc() {
    local out="${ISYNC_DIR}/mbsyncrc"
    local all_channels=()

    cat > "$out" <<'HDR'
# Generated by gen.sh — edit accounts/*.conf and re-run instead.

Create      Both
Expunge     Both
SyncState   *
HDR

    for f in "${accounts[@]}"; do
        load_account "$f"

        cat >> "$out" <<EOF

IMAPAccount ${ACCOUNT}
Host        ${IMAP_HOST}
Port        ${IMAP_PORT}
User        ${EMAIL}
PassCmd     "pass show ${PASS_ENTRY}"
AuthMechs   LOGIN
TLSType     IMAPS
CertificateFile /etc/ssl/certs/ca-certificates.crt

IMAPStore ${ACCOUNT}-remote
Account   ${ACCOUNT}

MaildirStore ${ACCOUNT}-local
Subfolders Verbatim
Path       ${MAIL_ROOT}/${ACCOUNT}/
Inbox      ${MAIL_ROOT}/${ACCOUNT}/Inbox

EOF

        if [[ "${TYPE}" == "gmail" ]]; then
            gmail_channels "${ACCOUNT}" >> "$out"
            all_channels+=("${ACCOUNT}-inbox" "${ACCOUNT}-sent" "${ACCOUNT}-drafts" "${ACCOUNT}-trash" "${ACCOUNT}-archive")
        else
            generic_channels "${ACCOUNT}" >> "$out"
            all_channels+=("${ACCOUNT}-inbox" "${ACCOUNT}-sent" "${ACCOUNT}-drafts" "${ACCOUNT}-trash")
        fi
    done

    {
        echo ""
        echo "Group all"
        printf 'Channel %s\n' "${all_channels[@]}"
    } >> "$out"

    chmod 600 "$out"
    info "isync/mbsyncrc"
}

# ─── Generate msmtp/config ───────────────────────────────────────────────────

gen_msmtp() {
    local out="${MSMTP_DIR}/config"
    local first=""

    cat > "$out" <<'HDR'
# Generated by gen.sh — edit accounts/*.conf and re-run instead.

defaults
auth           on
tls            on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        ~/.local/state/msmtp/msmtp.log
HDR

    for f in "${accounts[@]}"; do
        load_account "$f"
        [[ -z "$first" ]] && first="${ACCOUNT}"

        cat >> "$out" <<EOF

account ${ACCOUNT}
host    ${SMTP_HOST}
port    ${SMTP_PORT}
from    ${FROM_ADDRESS}
user    ${EMAIL}
passwordeval "pass show ${PASS_ENTRY}"
EOF
    done

    echo -e "\naccount default : ${first}" >> "$out"
    chmod 600 "$out"
    info "msmtp/config"
}

# ─── Generate mutt account files + init.muttrc ───────────────────────────────

gen_mutt() {
    mkdir -p "${MUTT_ACCOUNTS}"

    # Collect account names first (for building tab bar)
    local account_names=()
    for f in "${accounts[@]}"; do
        load_account "$f"
        account_names+=("${ACCOUNT}")
    done

    local first="" fkey=2
    local init="${MUTT_ACCOUNTS}/init.muttrc"
    local macros=""
    local folder_hooks=""

    for f in "${accounts[@]}"; do
        load_account "$f"
        [[ -z "$first" ]] && first="${ACCOUNT}"

        # Build tab bar: active account in [ brackets ]
        local tabs=""
        for name in "${account_names[@]}"; do
            if [[ "$name" == "${ACCOUNT}" ]]; then
                tabs+="[ ${name} ] "
            else
                tabs+=" ${name}  "
            fi
        done

        cat > "${MUTT_ACCOUNTS}/${ACCOUNT}.muttrc" <<EOF
# Generated by gen.sh — edit accounts/*.conf and re-run instead.

set my_account = "${ACCOUNT}"
set realname   = "${FULLNAME}"
set from       = "${FROM_ADDRESS}"
set sendmail   = "msmtp -a ${ACCOUNT}"

set folder    = "${MAIL_ROOT}/${ACCOUNT}"
set spoolfile = "+Inbox"
set record    = "+Sent"
set postponed = "+Drafts"
set trash     = "+Trash"

set header_cache     = ${CACHE_ROOT}/${ACCOUNT}/headers
set message_cachedir = ${CACHE_ROOT}/${ACCOUNT}/bodies
set mbox_type        = Maildir

unmailboxes *
mailboxes =Inbox =Sent =Drafts =Trash =Archive

set status_format = " ${tabs}│ %D %?u?  %u ?%?R?  %R ?%?F?  %F ? %> %P "

macro index o "<shell-escape>mbsync --config ~/.config/isync/mbsyncrc ${ACCOUNT} && notmuch new<enter>" "sync ${ACCOUNT}"

macro index \ef "<enter-command>unset wait_key<enter><shell-escape>read -p 'search ${ACCOUNT}: ' x; echo \\\$x >~/.cache/mutt_terms<enter><limit>~i \"\\\`notmuch search --output=messages \\\$(cat ~/.cache/mutt_terms) path:${ACCOUNT}/** | head -n 600 | perl -le '@a=<>;chomp@a;s/^id:// for@a;\\\$,=\"|\";print@a'\\\`\"<enter>" "search ${ACCOUNT} mail (notmuch)"
EOF
        info "mutt/accounts/${ACCOUNT}.muttrc"

        macros+="macro index,pager <F${fkey}> '<sync-mailbox><enter-command>source ~/.config/mutt/accounts/${ACCOUNT}.muttrc<enter><change-folder>!<enter>' \"switch to ${ACCOUNT}\""$'\n'
        fkey=$((fkey + 1))

        folder_hooks+="folder-hook '${MAIL_ROOT}/${ACCOUNT}/*' 'source ~/.config/mutt/accounts/${ACCOUNT}.muttrc'"$'\n'
    done

    cat > "$init" <<EOF
# Generated by gen.sh — edit accounts/*.conf and re-run instead.

source ~/.config/mutt/accounts/${first}.muttrc

${folder_hooks}
${macros}
EOF
    info "mutt/accounts/init.muttrc"
}

# ─── Generate notmuch/notmuchrc ──────────────────────────────────────────────

gen_notmuch() {
    mkdir -p "${NOTMUCH_DIR}/default"
    local out="${NOTMUCH_DIR}/default/config"
    local pname="" pemail="" others=""

    for f in "${accounts[@]}"; do
        load_account "$f"
        if [[ -z "$pname" ]]; then
            pname="${FULLNAME}"; pemail="${EMAIL}"
        else
            [[ -n "$others" ]] && others+=";"; others+="${EMAIL}"
        fi
    done

    cat > "$out" <<EOF
# Generated by gen.sh — edit accounts/*.conf and re-run instead.

[database]
path = ${MAIL_ROOT}

[user]
name = ${pname}
primary_email = ${pemail}
EOF
    [[ -n "$others" ]] && echo "other_email = ${others}" >> "$out"

    cat >> "$out" <<'TAIL'

[new]
tags = unread;inbox
ignore = .uidvalidity;.mbsyncstate

[search]
exclude_tags = deleted;spam

[maildir]
synchronize_flags = true
TAIL
    info "notmuch/default/config"
}

# ─── Create maildir + cache dirs ─────────────────────────────────────────────

create_dirs() {
    for f in "${accounts[@]}"; do
        load_account "$f"
        for box in Inbox Sent Drafts Trash Archive; do
            mkdir -p "${MAIL_ROOT}/${ACCOUNT}/${box}"/{cur,new,tmp}
        done
        mkdir -p "${CACHE_ROOT}/${ACCOUNT}"/{headers,bodies}
        info "dirs for ${ACCOUNT}"
    done
    mkdir -p "${HOME}/.local/state/msmtp"
}

# ─── Main ─────────────────────────────────────────────────────────────────────

echo "Generating configs for ${#accounts[@]} account(s)…"
echo

gen_mbsyncrc
gen_msmtp
gen_mutt
gen_notmuch
create_dirs

echo
info "Done. Sync with: mbsync --config ~/.config/isync/mbsyncrc --all && notmuch new"
